# Generated by Django 2.0.13 on 2019-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=15)),
                ('company_description', models.CharField(max_length=500)),
                ('working_position', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('e_mail', models.EmailField(max_length=60)),
                ('linked_in_reference', models.URLField(max_length=100)),
            ],
        ),
    ]
